highlighter: rouge
markdown: kramdown

title : WDR
tagline: wsadmin Jython library aiming at simplifying WebSphere Application Server scripting
keywords: WebSphere,wsadmin,Jython,automation,DevOps

disclaimer: All trademarks belong to their respective owners

baseurl: /WDR
url: https://wdr.github.io

google_analytics: 'UA-44124024-1'

github : WDR/WDR
