set WAS61_RUNTIME_HOME=C:\IBM\WebSphere61\AppClient
set WAS61_JYTHON_VERSION=2.1
set WAS70_RUNTIME_HOME=C:\IBM\WebSphere7\AppClient
set WAS70_JYTHON_VERSION=2.1
set WAS80_RUNTIME_HOME=C:\IBM\WebSphere80\AppClient
set WAS80_JYTHON_VERSION=2.1
set WAS85_RUNTIME_HOME=C:\IBM\WebSphere85\AppClient
set WAS85_JYTHON_VERSION=2.1
